name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PARENT_REPO: njfamirm/decap-cms-github-backend
  MAIN_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Get latest release from parent repo
        uses: oz-elhassid/get-latest-release@master
        id: keydb
        with:
          repository: ${{ env.PARENT_REPO }}
          and_filters: "prerelease: false, draft: false"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish latest release
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./.github/workflows/docker/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ steps.keydb.outputs.tag_name }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:latest \
          --build-arg GIT_TAG=${{ steps.keydb.outputs.tag_name }} \
          --push .

      - name: Publish latest commit
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file ./.github/workflows/docker/Dockerfile \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:build-$(git rev-parse --short "$(git ls-remote https://github.com/${{ env.PARENT_REPO }}.git HEAD | cut -f 1)") \
          --build-arg GIT_TAG=${{ env.MAIN_BRANCH }} \
          --push .
